export const CREATE_MENTOR_REQUEST = "CREATE_MENTOR_REQUEST";
export const CREATE_MENTOR_SUCCESS = "CREATE_MENTOR_SUCCESS";
export const CREATE_MENTOR_FAIL = "CREATE_MENTOR_FAIL";

export const CREATE_STUDENT_REQUEST = "CREATE_STUDENT_REQUEST";
export const CREATE_STUDENT_SUCCESS = "CREATE_STUDENT_SUCCESS";
export const CREATE_STUDENT_FAIL = "CREATE_STUDENT_FAIL";

export const FETCH_STUDENTS_REQUEST = "FETCH_STUDENTS_REQUEST"
export const FETCH_STUDENTS_SUCCESS = "FETCH_STUDENTS_SUCCESS"
export const FETCH_STUDENTS_FAIL = "FETCH_STUDENTS_FAIL"

export const FETCH_MENTORS_REQUEST = "FETCH_MENTORS_REQUEST"
export const FETCH_MENTORS_SUCCESS = "FETCH_MENTORS_SUCCESS"
export const FETCH_MENTORS_FAIL = "FETCH_MENTORS_FAIL"

export const CREATE_STUDENTSTOMENTOR_REQUEST = "CREATE_STUDENTSTOMENTOR_REQUEST"
export const CREATE_STUDENTSTOMENTOR_SUCCESS = "CREATE_STUDENTSTOMENTOR_SUCCESS"
export const CREATE_STUDENTSTOMENTOR_FAIL = "CREATE_STUDENTSTOMENTOR_FAIL"

export const CREATE_CHANGEMENTORFORSTUDENT_REQUEST = " CREATE_CHANGEMENTORFORSTUDENT_REQUEST";
export const CREATE_CHANGEMENTORFORSTUDENT_SUCCESS = " CREATE_CHANGEMENTORFORSTUDENT_SUCCESS";
export const CREATE_CHANGEMENTORFORSTUDENT_FAIL = " CREATE_CHANGEMENTORFORSTUDENT_FAIL";

export const FETCH_MENTORSTUDENTS_REQUEST = "FETCH_MENTORSTUDENTS_REQUEST"
export const FETCH_MENTORSTUDENTS_SUCCESS = "FETCH_MENTORSTUDENTS_SUCCESS"
export const FETCH_MENTORSTUDENTS_FAIL = "FETCH_MENTORSTUDENTS_FAIL"